/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bake.examenbanco;

import javax.swing.*;

/**
 *
 * @author Acer
 */
public class BankGUI extends javax.swing.JFrame {

    private JTextArea textArea = new JTextArea(20,40);
    private Banco banco;
    
    /**
     * Creates new form BankGUI
     */
    public BankGUI() {
        banco = new Banco();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnMostrarCuentas = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnLogsDeposito = new javax.swing.JButton();
        btnLogsRetiro = new javax.swing.JButton();
        btnAlmacenarLogs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(242, 208, 169));

        Header.setBackground(new java.awt.Color(241, 227, 211));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco Sunshine");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnEliminarCuenta.setText("Eliminar Cuenta");
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });

        btnRetiro.setText("Retiro");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        btnMostrarCuentas.setText("Mostrar Cuentas");
        btnMostrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCuentasActionPerformed(evt);
            }
        });

        btnVerificar.setText("Verificar Cuenta");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnDeposito.setText("Deposito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        btnLogsDeposito.setText("Consultar Logs Deposito");
        btnLogsDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsDepositoActionPerformed(evt);
            }
        });

        btnLogsRetiro.setText("Consultar Logs Retiro");
        btnLogsRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsRetiroActionPerformed(evt);
            }
        });

        btnAlmacenarLogs.setText("Almacenar Logs");
        btnAlmacenarLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenarLogsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(btnLogsDeposito)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVerificar)
                                            .addComponent(btnCrearCuenta))
                                        .addGap(63, 63, 63)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEliminarCuenta)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                                .addComponent(btnRetiro)
                                                .addGap(21, 21, 21)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMostrarCuentas)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                                .addComponent(btnDeposito)
                                                .addGap(13, 13, 13))))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnLogsRetiro)
                                        .addGap(13, 13, 13)))
                                .addGap(29, 29, 29)))))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnAlmacenarLogs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCuenta)
                    .addComponent(btnEliminarCuenta)
                    .addComponent(btnMostrarCuentas))
                .addGap(41, 41, 41)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar)
                    .addComponent(btnRetiro)
                    .addComponent(btnDeposito))
                .addGap(40, 40, 40)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogsDeposito)
                    .addComponent(btnLogsRetiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAlmacenarLogs)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        JTextField numId = new JTextField();
        JTextField numeroCuenta = new JTextField();
        JTextField saldo = new JTextField();
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Numero de Identidad: "));
        panel.add(numId);
        panel.add(new JLabel("Numero de Cuenta: "));
        panel.add(numeroCuenta);
        panel.add(new JLabel("Saldo: "));
        panel.add(saldo);
        
        //Panel de dialogo
        int result = JOptionPane.showConfirmDialog(null, panel,"Crear",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        //Ver si se hizo cloc en OK
        if (result == JOptionPane.OK_OPTION) {
            //Datos de usuario
            String numIdentidad = numId.getText();
            String numCuenta = numeroCuenta.getText();
            double saldoCuenta;
            try {
                saldoCuenta = Double.parseDouble(saldo.getText());
                
                //Crear solicitud
                Cuenta nuevaCuenta = new Cuenta(numCuenta,saldoCuenta, "MXN");
                banco.agregarCuenta(numIdentidad,nuevaCuenta); // Agrega cuenta al banco
                JOptionPane.showMessageDialog(null, "Cuenta creada correctamente");
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "El saldo deber ser un numero valido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        JTextField numIdentField = new JTextField(10);
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Ingrese el numero de identidad de la cuenta que quiere eliminar:"));
        panel.add(numIdentField);
        
        int result = JOptionPane.showConfirmDialog(null, panel,"Agregar Solicitud",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            //Numero del usuario a eliminar
            String numIdentidad = numIdentField.getText();
            
            //Buscar cuenta
            boolean cuentaEncontrada = false;
            for (int i = 0; i < banco.cuentas.Longitud(); i++) {
                Cuenta cuenta = banco.cuentas.Obtener(i);
                if (cuenta.getNumeroCuenta().equals(numIdentidad)) {
                    //Eliminar cuenta
                    banco.cuentas.Eliminar(i);
                    JOptionPane.showMessageDialog(null, "Cuenta eliminada exitosamente");
                    cuentaEncontrada = true;
                    break;
                }
            }
            //Mensaje si no la encuente
            if (!cuentaEncontrada) {
                JOptionPane.showMessageDialog(null, "No se encontro ninguna cuenta con el numero de identidad proporcionado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void btnMostrarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCuentasActionPerformed
        //Obtener numeo de identidad
        String numeroIDentidad = JOptionPane.showInputDialog("Ingrese el numero de identidad del cliente:");
         
        String cuentasCliente = banco.visualizarCuentasCliente(numeroIDentidad);
         
        textArea.setText(cuentasCliente);
        textArea.setEditable(false);
         
        //Mostrar en cuadro de dialogo
        JOptionPane.showMessageDialog(null,textArea,"Cuentas en el Banco", JOptionPane.INFORMATION_MESSAGE);
   
    }//GEN-LAST:event_btnMostrarCuentasActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        //Obtener datos
        JTextField nombre = new JTextField();
        JTextField numId = new JTextField();
        JTextField numeroCuenta = new JTextField();
        JTextField saldo = new JTextField();
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Nombre depositante:"));
        panel.add(nombre);
        panel.add(new JLabel("Numero de Identidad: "));
        panel.add(numId);
        panel.add(new JLabel("Numero de Cuenta: "));
        panel.add(numeroCuenta);
        panel.add(new JLabel("Saldo: "));
        panel.add(saldo);
        
        //Panel de dialogo
        int result = JOptionPane.showConfirmDialog(null, panel,"Crear",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        //Ver si se hizo cloc en OK
        if (result == JOptionPane.OK_OPTION) {
            //Datos de usuario
            String numIdentidad = numId.getText();
            String nombrePersona = nombre.getText();
            String numCuenta = numeroCuenta.getText();
            double saldoCuenta;
            try {
                saldoCuenta = Double.parseDouble(saldo.getText());
                
                banco.depositar(numIdentidad,numCuenta,saldoCuenta,nombrePersona); // Agrega cuenta al banco
                JOptionPane.showMessageDialog(null, "Deposito exitoso");
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "El saldo deber ser un numero valido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        ListaSE<Cuenta> cuentas = banco.cuentas;
        
        if (!cuentas.EsVacia()) {
            String cuentaInfo = "Cuentas en el banco: \n";
            
            for (int i = 0; i < banco.cuentas.Longitud(); i++) {
            Cuenta cuenta = banco.cuentas.Obtener(i);
            cuentaInfo += ("Cuenta " + (i+1) +":");
            cuentaInfo += ("Numero de identidad: " +cuenta.getNumeroCuenta()+ "\n");
            cuentaInfo += ("Saldo Actual: " + cuenta.getSaldo()+ "\n");
            } 
            JOptionPane.showMessageDialog(null, cuentaInfo, "Cuentas en el Banco" ,JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, " No hay cuentas en el banco.");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        //Abrir cuadro de dialogo
        JTextField txtNumeroIdentidad = new JTextField();
        JTextField txtCantidad = new JTextField();
        JTextField txtNumeroCuenta = new JTextField();
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(new JLabel("Número Identidad:"));
        panel.add(txtNumeroIdentidad);
        panel.add(new JLabel("Cantidad:"));
        panel.add(txtCantidad);
        panel.add(new JLabel("Número Cuenta:"));
        panel.add(txtNumeroCuenta);
        
        int result = JOptionPane.showConfirmDialog(null, panel,"Agregar Solicitud",
                     JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            //Datos de usuario
            String numIdentidad = txtNumeroIdentidad.getText();
            double cantidad;
            String numeroCuenta = txtNumeroCuenta.getText();
         
            try {
                cantidad = Double.parseDouble(txtCantidad.getText());
                
                banco.retirar(numIdentidad, numeroCuenta, cantidad);
                JOptionPane.showMessageDialog(null, "Retiro exitoso");
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "La cantidad deber ser un numero valido","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnLogsDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsDepositoActionPerformed
        String logsDepositos = banco.consultarLogDepositos();
        textArea.setText(logsDepositos);
    }//GEN-LAST:event_btnLogsDepositoActionPerformed

    private void btnLogsRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsRetiroActionPerformed
        String logsRetiros = banco.consultarLogRetiros();
        textArea.setText(logsRetiros);
    }//GEN-LAST:event_btnLogsRetiroActionPerformed

    private void btnAlmacenarLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenarLogsActionPerformed
        banco.almacenarLogDeposito();
        banco.almacenarLogsRetiro();
    }//GEN-LAST:event_btnAlmacenarLogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnAlmacenarLogs;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnLogsDeposito;
    private javax.swing.JButton btnLogsRetiro;
    private javax.swing.JButton btnMostrarCuentas;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
